# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestSdkDemo' do
  
  # Pods for TestSdkDemo
  pod 'LogicalProgram', :path => "../LogicalProgram" 

end
